version: '3.2'
services: 
  elasticsearch:
    build: 
      context: ./elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes: 
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports: 
      - "9200:9200"
      - "9300:9300"
    environment: 
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: password
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks: 
      - elastic
  kibana:
    build: 
      context: ./kibana/
      args: 
        ELK_VERSION: $ELK_VERSION
    volumes: 
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports: 
      - "5601:5601"
    networks: 
      - elastic
    depends_on: 
      - elasticsearch
  filebeat:
    build: 
      context: ./filebeat/
      args: 
        ELK_VERSION: $ELK_VERSION
    user: root
    volumes: 
      - type: bind
        source: ./filebeat/config/filebeat.yml
        target: /usr/share/filebeat/filebeat.yml
        read_only: true
      - type: bind
        source: /var/lib/docker/containers
        target: /var/lib/docker/containers
        read_only: true
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
      - type: volume
        source: ehrlogs
        target: /var/log/ehr
    depends_on: 
      - elasticsearch
      - kibana
    networks: 
      - elastic
    links: 
      - elasticsearch
      - kibana
  backend: 
    build: 
      context: ./backend
    volumes: 
      - type: volume
        source: ehrlogs
        target: /usr/app/logs
    networks: 
      - elastic
    ports: 
      - "8080:8080"
networks: 
  elastic:
    driver: bridge
volumes: 
  elasticsearch:
    driver: local
  ehrlogs:
    driver: local
